import axios from 'axios'
import Head from 'next/head'
import Image from 'next/image'
import Header from '../components/Header'
import HomeContent from '../components/HomeContent'

export default function Home({ users }) {
  return (
    <div>
      <Head>
        <title>ADmyBRAND | Coding Challenge</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />
      <HomeContent users={users} />
    </div>
  )
}

export async function getServerSideProps(ctx) {

  try {
    // fetch users using axios
    const { data } = await axios.get("https://jsonplaceholder.typicode.com/users")

    return {
      props: {
        "users": data
      }
    }
  } catch (err) {

    return {
      notFound: true
    }
  }


}
