import type { NextPage } from 'next'
import React, { useState, useEffect } from 'react';
import Head from 'next/head'
import Form from '../components/form';
import type { FetchInterface, PostInterface } from './api/types';
import { fetchData } from './api/fetchAndPostJson';
import Maps from '../components/maps';

const Home: NextPage = () => {
	const [ userData, setUserData ] = useState<FetchInterface[] | null>(null);
	const [ userId, setUserId ] = useState<number>(0);
	const [ title, setTitle ] = useState<string>('');
	const [ body, setBody] = useState<string>('');

	const [ printErrorMessage, setPrintErrorMessage ] = useState<string>('');

	useEffect(() => {
        if (userData === null) {
            fetchData()
				.then(res => setUserData(res))
				.catch(() => setPrintErrorMessage('**The Data could not be loaded. Refresh or Check Connection'));
        }
    }, [ userData ]);

	return (
		<div>
			<Head>
				<title>Coding Challenge Frontend</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<div className="main-container">
				<div className="form-container">
					<h4 className="error-message">{ printErrorMessage }</h4>
					<Form
						userData={ userData }
						setUserData={ setUserData }
						userId={ userId }
						setUserId={ setUserId }
						title={ title }
						setTitle={ setTitle }
						body={ body }
						setBody={ setBody }
					/>
				</div>
				<div>
					<h1>Maps</h1>
					<Maps userData={ userData } userId={ userId } /> 
				</div>
			</div>
		</div>
	);
}

export default Home
