import Head from 'next/head';

import { FormControl } from './components/FormControl';

export default function Home({ users }) {

  const TitleErrorMessage = 'Special Characters not allowed';
  const DescriptionErrorMessage = 'Please enter atleast 6 characters';

  return (
    <div>
      <Head>
        <title>ADmyBRAND India</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <FormControl
        users={users}
        TitleErrorMessage={TitleErrorMessage}
        DescriptionErrorMessage={DescriptionErrorMessage}
      />
    </div>
  )
}

export async function getStaticProps() {
  const response = await fetch('https://jsonplaceholder.typicode.com/users');
  const data = await response.json();
  return {
    props: {
      users: data
    }
  }
}