import Head from "next/head";
import Dashboard from "../components/Dashboard";
import { useState } from "react";

export const getStaticProps = async () => {
  try{
    const res = await fetch("https://jsonplaceholder.typicode.com/users");
    const data = await res.json();    
    return {
      props: {
        data,
      },
    };
  }catch(e){
    return {
      notFound: true
    }
  }
  
};

export default function Home({ data }) {  
  const [Element, setElement] = useState(null);
  const getId = (ele, data) => {
    const value = data.filter((x) => {
      return x.id == ele;
    });
    setElement(value);
  };
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="Main">
        <div className="mainList">
          <>
            {data.map((curElem) => {
              return (
                <button className="list" key={curElem.id}>
                  <a onClick={() => getId(curElem.id, data)}>{curElem.name}</a>
                </button>
              );
            })}
          </>
        </div>
        {Element != null ? (
          <Dashboard element={Element} />
        ) : (
          <div className="select">Please Select a user</div>
        )}
      </div>
    </>
  );
}
