import Head from "next/head";
import styles from "../styles/Home.module.css";
import "mapbox-gl/dist/mapbox-gl.css";
import dynamic from "next/dynamic";
// import Form from "../components/Form";
const Form = dynamic(() => import("../components/Form"), { ssr: false });

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Post</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Form />
      </main>
    </div>
  );
}
